name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode 16
      run: sudo xcode-select -switch /Applications/Xcode_16.0.app/Contents/Developer
    
    - name: List Available Simulators
      run: xcrun simctl list devices available
    
    - name: Reset Simulators
      run: |
        echo "Resetting all simulators to clean state..."
        xcrun simctl shutdown all
        xcrun simctl erase all
        
    - name: Build and Test
      timeout-minutes: 20
      run: |
        echo "Building and testing..."
        
        # Use the first available iPhone 16 simulator
        xcodebuild \
          -project WorkoutTracker.xcodeproj \
          -scheme WorkoutTracker \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -configuration Debug \
          clean build test \
          -only-testing:WorkoutTrackerTests \
          -disable-concurrent-testing \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          DerivedData/Logs/Test/*.xcresult