name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode 16
      run: sudo xcode-select -switch /Applications/Xcode_16.0.app/Contents/Developer
    
    - name: List Available Simulators
      run: xcrun simctl list devices available
    
    - name: Build and Test
      run: |
        # Use a known iPhone 16 simulator ID from the available destinations
        # From the output, we can see iPhone 16 with iOS 18.4 is available
        DEVICE_ID="1565B47A-C01C-4B4C-B660-9A278E27558D"
        
        echo "Attempting to use iPhone 16 simulator: $DEVICE_ID"
        
        # First try with the specific iPhone 16 device
        if xcodebuild \
          -scheme WorkoutTracker \
          -destination "platform=iOS Simulator,id=$DEVICE_ID" \
          -configuration Debug \
          clean build test \
          CODE_SIGNING_ALLOWED=NO; then
          echo "Tests completed successfully with iPhone 16 simulator"
        else
          echo "iPhone 16 simulator failed, trying with iPad simulator as fallback"
          xcodebuild \
            -scheme WorkoutTracker \
            -destination 'platform=iOS Simulator,id=2BF9F98D-7837-4C0F-BBC9-BDEAD8325D03' \
            -configuration Debug \
            clean build test \
            CODE_SIGNING_ALLOWED=NO
        fi
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          DerivedData/Logs/Test/*.xcresult